// <auto-generated />
using System;
using Chabloom.Ecommerce.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Chabloom.Ecommerce.Backend.Data.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedUser")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DisabledTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DisabledUser")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupMethodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedUser")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PickupMethodName");

                    b.HasIndex("StoreId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Orders.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderId", "ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("323565d2-3c93-4e05-81ff-ac745e22af9e"),
                            Amount = 299m,
                            CategoryId = new Guid("66272963-7577-4fb3-8cd6-a0bc411404e9"),
                            CurrencyId = "USD",
                            Description = "Our Organic Assam is a rich, full leaf, medium bodied black tea. It has a slightly lighter liquor, with sweet honey flavor.",
                            Name = "Organic Assam (25 tea bags)"
                        },
                        new
                        {
                            Id = new Guid("41e5e396-6757-42f3-9149-3b084976545a"),
                            Amount = 299m,
                            CategoryId = new Guid("66272963-7577-4fb3-8cd6-a0bc411404e9"),
                            CurrencyId = "USD",
                            Description = "Our Organic Assam is a rich, full leaf, medium bodied black tea. It has a slightly lighter liquor, with sweet honey flavor.",
                            Name = "Organic Assam (cup)"
                        },
                        new
                        {
                            Id = new Guid("78e540de-d2b3-4b1f-bb1e-988be3245088"),
                            Amount = 499m,
                            CategoryId = new Guid("cf059c18-ec58-4c6e-ae61-4dddabd61a6d"),
                            CurrencyId = "USD",
                            Description = "Our friends at Puttabong have done a great job with this tea. It is owned by Jayshree and is located north of Darjeeling town.  This tea came towards the end of the First Flush season in April. Brisk yet flavorful. Hats off!",
                            Name = "Puttabong 1st Flush Darjeeling (25 tea bags)"
                        },
                        new
                        {
                            Id = new Guid("4d0bcd02-9dab-499e-92cd-8ba9f252b2a9"),
                            Amount = 499m,
                            CategoryId = new Guid("cf059c18-ec58-4c6e-ae61-4dddabd61a6d"),
                            CurrencyId = "USD",
                            Description = "Our friends at Puttabong have done a great job with this tea. It is owned by Jayshree and is located north of Darjeeling town.  This tea came towards the end of the First Flush season in April. Brisk yet flavorful. Hats off!",
                            Name = "Puttabong 1st Flush Darjeeling (cup)"
                        },
                        new
                        {
                            Id = new Guid("cb949dda-57fb-4731-8379-b6f955b3102e"),
                            Amount = 299m,
                            CategoryId = new Guid("6470ca64-4d0a-4d94-8333-0f06d74e7ca1"),
                            CurrencyId = "USD",
                            Description = "It seems like it is Yuzu’s time to shine. People are really liking this citrus fruit from Japan. So when we saw a blend of nice Sencha and Yuzu, we thought we should try it.",
                            Name = "Yuzu Sencha (25 tea bags)"
                        },
                        new
                        {
                            Id = new Guid("0418ae94-b020-4b2a-9697-7ddcbe2bd72a"),
                            Amount = 299m,
                            CategoryId = new Guid("6470ca64-4d0a-4d94-8333-0f06d74e7ca1"),
                            CurrencyId = "USD",
                            Description = "It seems like it is Yuzu’s time to shine. People are really liking this citrus fruit from Japan. So when we saw a blend of nice Sencha and Yuzu, we thought we should try it.",
                            Name = "Yuzu Sencha (cup)"
                        },
                        new
                        {
                            Id = new Guid("5e152dc1-203d-45e0-9eee-acc6f8bb74ee"),
                            Amount = 399m,
                            CategoryId = new Guid("b5e4f99f-227e-49be-a82f-8b4e06d35d96"),
                            CurrencyId = "USD",
                            Description = "Matcha powdered green tea has been the pride of Uji for several centuries. This organic grade is great for everyday use.",
                            Name = "Organic Matcha (25 tea bags)"
                        },
                        new
                        {
                            Id = new Guid("e95543da-bb67-4859-8b98-d92041d58d8d"),
                            Amount = 399m,
                            CategoryId = new Guid("b5e4f99f-227e-49be-a82f-8b4e06d35d96"),
                            CurrencyId = "USD",
                            Description = "Matcha powdered green tea has been the pride of Uji for several centuries. This organic grade is great for everyday use.",
                            Name = "Organic Matcha (cup)"
                        },
                        new
                        {
                            Id = new Guid("ce3e245b-75c5-418e-98fe-3a115aa7395d"),
                            Amount = 299m,
                            CategoryId = new Guid("7d582944-4e2f-42ee-8a1e-199fd58762a6"),
                            CurrencyId = "USD",
                            Description = "For beautiful Strawberry Kiwi Fruit Tea, we blend strawberries and dried fruit pieces with strawberry and kiwi flavors to create a vibrant ruby red drink. It looks festive brewed in a glass teapot, and tastes delicious hot or iced. ",
                            Name = "Strawberry Kiwi Fruit Tea (25 tea bags)"
                        },
                        new
                        {
                            Id = new Guid("728617aa-ecd3-48ac-bdad-ccf660f775a3"),
                            Amount = 299m,
                            CategoryId = new Guid("7d582944-4e2f-42ee-8a1e-199fd58762a6"),
                            CurrencyId = "USD",
                            Description = "For beautiful Strawberry Kiwi Fruit Tea, we blend strawberries and dried fruit pieces with strawberry and kiwi flavors to create a vibrant ruby red drink. It looks festive brewed in a glass teapot, and tastes delicious hot or iced. ",
                            Name = "Strawberry Kiwi Fruit Tea (cup)"
                        },
                        new
                        {
                            Id = new Guid("0321e99e-dd3b-402f-9cf6-e2ba284862d0"),
                            Amount = 299m,
                            CategoryId = new Guid("7d582944-4e2f-42ee-8a1e-199fd58762a6"),
                            CurrencyId = "USD",
                            Description = "Our Blood Orange Fruit Tea, a brilliant blend of dried fruit, has the lovely and distinctive twist found in blood oranges. Delicious hot or cold, it brews an aromatic and vivid shade of orange.",
                            Name = "Blood Orange Fruit Tea (25 tea bags)"
                        },
                        new
                        {
                            Id = new Guid("2446bd16-df0a-4f7e-9e23-18cb1d5d008e"),
                            Amount = 299m,
                            CategoryId = new Guid("7d582944-4e2f-42ee-8a1e-199fd58762a6"),
                            CurrencyId = "USD",
                            Description = "Our Blood Orange Fruit Tea, a brilliant blend of dried fruit, has the lovely and distinctive twist found in blood oranges. Delicious hot or cold, it brews an aromatic and vivid shade of orange.",
                            Name = "Blood Orange Fruit Tea (cup)"
                        },
                        new
                        {
                            Id = new Guid("9aa49ae2-53bb-417a-b1f7-1bd9f6578969"),
                            Amount = 599m,
                            CategoryId = new Guid("1def1630-85ef-4a97-a073-fd3ba814bab0"),
                            CurrencyId = "USD",
                            Description = "Bud Light is a premium beer with incredible drinkability that has made it a top selling American beer that everybody knows and loves. This light beer is brewed using a combination of barley malts, rice and a blend of premium aroma hop varieties. Featuring a fresh, clean taste with subtle hop aromas, this light lager delivers ultimate refreshment with its delicate malt sweetness and crisp finish.",
                            Name = "Beer"
                        },
                        new
                        {
                            Id = new Guid("0aecbbc7-0e6c-4727-bc05-9d3700397b00"),
                            Amount = 499m,
                            CategoryId = new Guid("1def1630-85ef-4a97-a073-fd3ba814bab0"),
                            CurrencyId = "USD",
                            Description = "Designed to be a great tasting water, our water is filtered by reverse osmosis to remove impurities, then enhanced with a special blend of minerals for a pure, crisp, fresh taste.",
                            Name = "Water"
                        },
                        new
                        {
                            Id = new Guid("781d9646-1156-4cbb-a581-329f2ae34744"),
                            Amount = 399m,
                            CategoryId = new Guid("f2b822fc-4e6e-4c65-a5bb-74d080c9e33a"),
                            CurrencyId = "USD",
                            Description = "The original burger starts with a 100% pure beef burger seasoned with just a pinch of salt and pepper. Then, the burger is topped with a tangy pickle, chopped onions, ketchup and mustard.",
                            Name = "Hamburger"
                        },
                        new
                        {
                            Id = new Guid("c615100b-e2d9-48a4-81c1-824a3bb12cb7"),
                            Amount = 199m,
                            CategoryId = new Guid("f2b822fc-4e6e-4c65-a5bb-74d080c9e33a"),
                            CurrencyId = "USD",
                            Description = "Our tasty all beef hot dogs are all natural, skinless, uncured and made with beef that’s never given antibiotics.",
                            Name = "Hot dog"
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TenantId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b3a059d-4cda-46cc-890e-2c1f6451d6d6"),
                            Description = "While black teas are made from the same Camellia sinensis plant as all teas, the oxidation and processing is what distinguishes black teas from the rest. Premium black teas are withered, rolled, oxidized and fired in an oven, creating a warm and toasty flavor. The lengthier oxidation process causes the tea leaves to develop into dark brown and black colors. The flavors can range from malty or smokey to fruity and sweet. Black teas range from mellow teas from China to full-bodied teas from Assam, India.",
                            Name = "Black",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("66272963-7577-4fb3-8cd6-a0bc411404e9"),
                            Description = "Assam is India's largest producer of tea, and the broad flood plains make for some of the most fertile tea estates in the world.",
                            Name = "Assam",
                            ParentCategoryId = new Guid("7b3a059d-4cda-46cc-890e-2c1f6451d6d6"),
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("cf059c18-ec58-4c6e-ae61-4dddabd61a6d"),
                            Description = "The light and brisk First Flush teas focus your attention. While the darker teas of the later seasons are more mellow and often have wonderful flavors.",
                            Name = "Darjeeling",
                            ParentCategoryId = new Guid("7b3a059d-4cda-46cc-890e-2c1f6451d6d6"),
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("6470ca64-4d0a-4d94-8333-0f06d74e7ca1"),
                            Description = "All green teas originate from the same species, the Camelia Sinensis. To make green tea, the fresh tea leaves are briefly cooked using either steam or dry heat. This process fixes the green colors and fresh flavors. The Chinese green teas are more mellow and smooth, while the Japanese green teas have the heft of rich, vegetal flavors, which comes from preservation of the chlorophyll.The general rule is that a cup of green tea contains about one-third as much caffeine as a cup of coffee. Green tea production methods vary but the focus is always to fix the green color. Thus, green teas are not oxidized.",
                            Name = "Green",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("b5e4f99f-227e-49be-a82f-8b4e06d35d96"),
                            Description = "Powdered green teas have been consumed in China and Japan for centuries. However it is only in the last few decades that Westerners have acquired a taste for this ancient tea. We enjoy the bracing vegetal flavors, as well as the unusual process for preparing the tea.",
                            Name = "Matcha",
                            ParentCategoryId = new Guid("6470ca64-4d0a-4d94-8333-0f06d74e7ca1"),
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("7d582944-4e2f-42ee-8a1e-199fd58762a6"),
                            Description = "Herbal teas, also known as herbal infusions, are typically a blend of herbs, flowers, spices, and dried fruit. This blend of ingredients is then brewed in the same way as your favorite traditional tea, either loose or in tea sachets or bags. By combining quality ingredients, blends can be created that calm, invigorate, or treat minor ailments. Colors and flavors range from light and fruity to vibrant and spicy, to match your mood.",
                            Name = "Herbal",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("1def1630-85ef-4a97-a073-fd3ba814bab0"),
                            Description = "Drinks",
                            Name = "Drinks",
                            TenantId = new Guid("9cafce7f-d4a1-4874-b3c9-339836fd082c")
                        },
                        new
                        {
                            Id = new Guid("f2b822fc-4e6e-4c65-a5bb-74d080c9e33a"),
                            Description = "Food",
                            Name = "Food",
                            TenantId = new Guid("9cafce7f-d4a1-4874-b3c9-339836fd082c")
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.ProductImage", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Name", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Name = "323565D2-3C93-4E05-81FF-AC745E22AF9E.webp",
                            ProductId = new Guid("323565d2-3c93-4e05-81ff-ac745e22af9e")
                        },
                        new
                        {
                            Name = "323565D2-3C93-4E05-81FF-AC745E22AF9E.webp",
                            ProductId = new Guid("41e5e396-6757-42f3-9149-3b084976545a")
                        },
                        new
                        {
                            Name = "78E540DE-D2B3-4B1F-BB1E-988BE3245088.webp",
                            ProductId = new Guid("78e540de-d2b3-4b1f-bb1e-988be3245088")
                        },
                        new
                        {
                            Name = "78E540DE-D2B3-4B1F-BB1E-988BE3245088.webp",
                            ProductId = new Guid("4d0bcd02-9dab-499e-92cd-8ba9f252b2a9")
                        },
                        new
                        {
                            Name = "CB949DDA-57FB-4731-8379-B6F955B3102E.webp",
                            ProductId = new Guid("cb949dda-57fb-4731-8379-b6f955b3102e")
                        },
                        new
                        {
                            Name = "CB949DDA-57FB-4731-8379-B6F955B3102E.webp",
                            ProductId = new Guid("0418ae94-b020-4b2a-9697-7ddcbe2bd72a")
                        },
                        new
                        {
                            Name = "5E152DC1-203D-45E0-9EEE-ACC6F8BB74EE.webp",
                            ProductId = new Guid("5e152dc1-203d-45e0-9eee-acc6f8bb74ee")
                        },
                        new
                        {
                            Name = "5E152DC1-203D-45E0-9EEE-ACC6F8BB74EE.webp",
                            ProductId = new Guid("e95543da-bb67-4859-8b98-d92041d58d8d")
                        },
                        new
                        {
                            Name = "CE3E245B-75C5-418E-98FE-3A115AA7395D.webp",
                            ProductId = new Guid("ce3e245b-75c5-418e-98fe-3a115aa7395d")
                        },
                        new
                        {
                            Name = "CE3E245B-75C5-418E-98FE-3A115AA7395D.webp",
                            ProductId = new Guid("728617aa-ecd3-48ac-bdad-ccf660f775a3")
                        },
                        new
                        {
                            Name = "0321E99E-DD3B-402F-9CF6-E2BA284862D0.webp",
                            ProductId = new Guid("0321e99e-dd3b-402f-9cf6-e2ba284862d0")
                        },
                        new
                        {
                            Name = "0321E99E-DD3B-402F-9CF6-E2BA284862D0.webp",
                            ProductId = new Guid("2446bd16-df0a-4f7e-9e23-18cb1d5d008e")
                        },
                        new
                        {
                            Name = "9AA49AE2-53BB-417A-B1F7-1BD9F6578969.webp",
                            ProductId = new Guid("9aa49ae2-53bb-417a-b1f7-1bd9f6578969")
                        },
                        new
                        {
                            Name = "0AECBBC7-0E6C-4727-BC05-9D3700397B00.webp",
                            ProductId = new Guid("0aecbbc7-0e6c-4727-bc05-9d3700397b00")
                        },
                        new
                        {
                            Name = "781D9646-1156-4CBB-A581-329F2AE34744.webp",
                            ProductId = new Guid("781d9646-1156-4cbb-a581-329f2ae34744")
                        },
                        new
                        {
                            Name = "C615100B-E2D9-48A4-81C1-824A3BB12CB7.webp",
                            ProductId = new Guid("c615100b-e2d9-48a4-81c1-824a3bb12cb7")
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.ProductPickupMethod", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickupMethodName")
                        .HasColumnType("text");

                    b.HasKey("ProductId", "PickupMethodName");

                    b.HasIndex("PickupMethodName");

                    b.ToTable("ProductPickupMethods");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("323565d2-3c93-4e05-81ff-ac745e22af9e"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("323565d2-3c93-4e05-81ff-ac745e22af9e"),
                            PickupMethodName = "Shipping"
                        },
                        new
                        {
                            ProductId = new Guid("41e5e396-6757-42f3-9149-3b084976545a"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("78e540de-d2b3-4b1f-bb1e-988be3245088"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("78e540de-d2b3-4b1f-bb1e-988be3245088"),
                            PickupMethodName = "Shipping"
                        },
                        new
                        {
                            ProductId = new Guid("4d0bcd02-9dab-499e-92cd-8ba9f252b2a9"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("cb949dda-57fb-4731-8379-b6f955b3102e"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("cb949dda-57fb-4731-8379-b6f955b3102e"),
                            PickupMethodName = "Shipping"
                        },
                        new
                        {
                            ProductId = new Guid("0418ae94-b020-4b2a-9697-7ddcbe2bd72a"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("5e152dc1-203d-45e0-9eee-acc6f8bb74ee"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("5e152dc1-203d-45e0-9eee-acc6f8bb74ee"),
                            PickupMethodName = "Shipping"
                        },
                        new
                        {
                            ProductId = new Guid("e95543da-bb67-4859-8b98-d92041d58d8d"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("ce3e245b-75c5-418e-98fe-3a115aa7395d"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("ce3e245b-75c5-418e-98fe-3a115aa7395d"),
                            PickupMethodName = "Shipping"
                        },
                        new
                        {
                            ProductId = new Guid("728617aa-ecd3-48ac-bdad-ccf660f775a3"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("0321e99e-dd3b-402f-9cf6-e2ba284862d0"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("0321e99e-dd3b-402f-9cf6-e2ba284862d0"),
                            PickupMethodName = "Shipping"
                        },
                        new
                        {
                            ProductId = new Guid("2446bd16-df0a-4f7e-9e23-18cb1d5d008e"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("9aa49ae2-53bb-417a-b1f7-1bd9f6578969"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("9aa49ae2-53bb-417a-b1f7-1bd9f6578969"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("0aecbbc7-0e6c-4727-bc05-9d3700397b00"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("0aecbbc7-0e6c-4727-bc05-9d3700397b00"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("781d9646-1156-4cbb-a581-329f2ae34744"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("781d9646-1156-4cbb-a581-329f2ae34744"),
                            PickupMethodName = "In-Store"
                        },
                        new
                        {
                            ProductId = new Guid("c615100b-e2d9-48a4-81c1-824a3bb12cb7"),
                            PickupMethodName = "Pickup"
                        },
                        new
                        {
                            ProductId = new Guid("c615100b-e2d9-48a4-81c1-824a3bb12cb7"),
                            PickupMethodName = "In-Store"
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Stores.PickupMethod", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("PickupMethods");

                    b.HasData(
                        new
                        {
                            Name = "In-Store"
                        },
                        new
                        {
                            Name = "Pickup"
                        },
                        new
                        {
                            Name = "Delivery"
                        },
                        new
                        {
                            Name = "Shipping"
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Stores.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedUser")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DisabledTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DisabledUser")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedUser")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId")
                        .IsUnique();

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87ceed1b-c17d-4a46-b71e-a1b2b3417483"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            WarehouseId = new Guid("69070b35-9ed3-47dd-a919-300371f54634")
                        },
                        new
                        {
                            Id = new Guid("030a985e-fdf3-40d5-84dd-d88011061fb2"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            WarehouseId = new Guid("92a73aca-281a-4ce2-9970-a1d6fbb75802")
                        },
                        new
                        {
                            Id = new Guid("9819e16b-be09-4b40-be9b-5e0d8b33280c"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            WarehouseId = new Guid("2ae5474a-4702-4bd0-b12e-90bc644ee223")
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871"),
                            Name = "Joe's Tea Shop"
                        },
                        new
                        {
                            Id = new Guid("9cafce7f-d4a1-4874-b3c9-339836fd082c"),
                            Name = "Augusta Green Jackets"
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.TenantHost", b =>
                {
                    b.Property<string>("Hostname")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Hostname");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantHosts");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.TenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("NormalizedName", "TenantId");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("830c7015-ab6c-4988-a603-ae3dc532d3b7"),
                            ConcurrencyStamp = "0c8bb047-f0a6-4523-8110-fd4fed52b4ae",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("30f42a18-8821-4913-b562-33d46d28f158"),
                            ConcurrencyStamp = "4970a2ee-0273-4dc6-9775-0bd0b03bae29",
                            Name = "Manager",
                            NormalizedName = "MANAGER",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("6f2183cb-401c-4d7c-9c3c-abc0e420f4f3"),
                            ConcurrencyStamp = "96309c79-49c7-470a-8c25-749cec10e97d",
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            TenantId = new Guid("9cafce7f-d4a1-4874-b3c9-339836fd082c")
                        },
                        new
                        {
                            Id = new Guid("f6079515-7ed4-4bcf-b476-e747e31ebdbb"),
                            ConcurrencyStamp = "1000c177-6c40-4dff-a853-c36332b89186",
                            Name = "Manager",
                            NormalizedName = "MANAGER",
                            TenantId = new Guid("9cafce7f-d4a1-4874-b3c9-339836fd082c")
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasAlternateKey("NormalizedUserName", "TenantId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc9ff447-53ee-466d-9928-93d22d8495c0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "E069977E-0AC5-4E43-AC44-FA297AB43951",
                            Email = "mdcasey@chabloom.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MDCASEY@CHABLOOM.COM",
                            NormalizedUserName = "MDCASEY@CHABLOOM.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELYyWQtU3cVbIfdmk4LHrtYsKTiYVW7OAge27lolZ3I8D97OE4QQ6Yn4XwGhO8YPuQ==",
                            PhoneNumber = "+18036179564",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "C3KZM3I2WQCCAD7EVHRZQSGRFRX5MY3I",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871"),
                            TwoFactorEnabled = false,
                            UserName = "mdcasey@chabloom.com"
                        },
                        new
                        {
                            Id = new Guid("dcd60458-2c66-4902-9861-4e6a3075a60c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7265D536-0D5F-49EE-AE87-81C14D3D0BE1",
                            Email = "mdcasey@chabloom.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MDCASEY@CHABLOOM.COM",
                            NormalizedUserName = "MDCASEY@CHABLOOM.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELYyWQtU3cVbIfdmk4LHrtYsKTiYVW7OAge27lolZ3I8D97OE4QQ6Yn4XwGhO8YPuQ==",
                            PhoneNumber = "+18036179564",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "C3KZM3I2WQCCAD7EVHRZQSGRFRX5MY3I",
                            TenantId = new Guid("9cafce7f-d4a1-4874-b3c9-339836fd082c"),
                            TwoFactorEnabled = false,
                            UserName = "mdcasey@chabloom.com"
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DisabledTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DisabledUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedUser")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95d98c98-8c88-4a15-b3ae-9ddb9b10848b"),
                            Address = "500 Great SW Pkwy SW, Atlanta, GA 30336",
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Atlanta Warehouse",
                            Name = "Atlanta Warehouse",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("68a72052-18f4-4e2a-a165-c057f61f86b5"),
                            Address = "650 Gateway Center Dr, San Diego, CA 92102",
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "San Diego Warehouse",
                            Name = "San Diego Warehouse",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("69070b35-9ed3-47dd-a919-300371f54634"),
                            Address = "201 N Tryon St, Charlotte, NC 28202",
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Charlotte Store",
                            Name = "Charlotte Store",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("92a73aca-281a-4ce2-9970-a1d6fbb75802"),
                            Address = "199 Gough St, San Francisco, CA 94102",
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "San Fransisco Store",
                            Name = "San Fransisco Store",
                            TenantId = new Guid("6a7e29dc-9eff-4f0d-bb14-51f63f142871")
                        },
                        new
                        {
                            Id = new Guid("2ae5474a-4702-4bd0-b12e-90bc644ee223"),
                            Address = "187 Railroad Ave, North Augusta, SC 29841",
                            CreatedTimestamp = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedUser = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "SRP Park",
                            Name = "SRP Park",
                            TenantId = new Guid("9cafce7f-d4a1-4874-b3c9-339836fd082c")
                        });
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Warehouses.WarehouseProduct", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("WarehouseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("WarehouseProducts");

                    b.HasData(
                        new
                        {
                            WarehouseId = new Guid("95d98c98-8c88-4a15-b3ae-9ddb9b10848b"),
                            ProductId = new Guid("323565d2-3c93-4e05-81ff-ac745e22af9e"),
                            Count = 2131
                        },
                        new
                        {
                            WarehouseId = new Guid("95d98c98-8c88-4a15-b3ae-9ddb9b10848b"),
                            ProductId = new Guid("78e540de-d2b3-4b1f-bb1e-988be3245088"),
                            Count = 0
                        },
                        new
                        {
                            WarehouseId = new Guid("95d98c98-8c88-4a15-b3ae-9ddb9b10848b"),
                            ProductId = new Guid("cb949dda-57fb-4731-8379-b6f955b3102e"),
                            Count = 9753
                        },
                        new
                        {
                            WarehouseId = new Guid("95d98c98-8c88-4a15-b3ae-9ddb9b10848b"),
                            ProductId = new Guid("5e152dc1-203d-45e0-9eee-acc6f8bb74ee"),
                            Count = 1239
                        },
                        new
                        {
                            WarehouseId = new Guid("95d98c98-8c88-4a15-b3ae-9ddb9b10848b"),
                            ProductId = new Guid("ce3e245b-75c5-418e-98fe-3a115aa7395d"),
                            Count = 1327
                        },
                        new
                        {
                            WarehouseId = new Guid("95d98c98-8c88-4a15-b3ae-9ddb9b10848b"),
                            ProductId = new Guid("0321e99e-dd3b-402f-9cf6-e2ba284862d0"),
                            Count = 1237
                        },
                        new
                        {
                            WarehouseId = new Guid("68a72052-18f4-4e2a-a165-c057f61f86b5"),
                            ProductId = new Guid("323565d2-3c93-4e05-81ff-ac745e22af9e"),
                            Count = 7865
                        },
                        new
                        {
                            WarehouseId = new Guid("68a72052-18f4-4e2a-a165-c057f61f86b5"),
                            ProductId = new Guid("78e540de-d2b3-4b1f-bb1e-988be3245088"),
                            Count = 0
                        },
                        new
                        {
                            WarehouseId = new Guid("68a72052-18f4-4e2a-a165-c057f61f86b5"),
                            ProductId = new Guid("cb949dda-57fb-4731-8379-b6f955b3102e"),
                            Count = 1231
                        },
                        new
                        {
                            WarehouseId = new Guid("68a72052-18f4-4e2a-a165-c057f61f86b5"),
                            ProductId = new Guid("5e152dc1-203d-45e0-9eee-acc6f8bb74ee"),
                            Count = 6655
                        },
                        new
                        {
                            WarehouseId = new Guid("68a72052-18f4-4e2a-a165-c057f61f86b5"),
                            ProductId = new Guid("ce3e245b-75c5-418e-98fe-3a115aa7395d"),
                            Count = 1235
                        },
                        new
                        {
                            WarehouseId = new Guid("68a72052-18f4-4e2a-a165-c057f61f86b5"),
                            ProductId = new Guid("0321e99e-dd3b-402f-9cf6-e2ba284862d0"),
                            Count = 2313
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("TenantRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TenantUserClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "name",
                            ClaimValue = "Matthew Casey",
                            UserId = new Guid("dc9ff447-53ee-466d-9928-93d22d8495c0")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "name",
                            ClaimValue = "Matthew Casey",
                            UserId = new Guid("dcd60458-2c66-4902-9861-4e6a3075a60c")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("TenantUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TenantUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("dc9ff447-53ee-466d-9928-93d22d8495c0"),
                            RoleId = new Guid("830c7015-ab6c-4988-a603-ae3dc532d3b7")
                        },
                        new
                        {
                            UserId = new Guid("dcd60458-2c66-4902-9861-4e6a3075a60c"),
                            RoleId = new Guid("6f2183cb-401c-4d7c-9c3c-abc0e420f4f3")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TenantUserTokens");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Orders.Order", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Stores.PickupMethod", "PickupMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PickupMethodName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Stores.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupMethod");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Orders.OrderProduct", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Orders.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.Product", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Products.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.ProductCategory", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Products.ProductCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCategory");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.ProductImage", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Products.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.ProductPickupMethod", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Stores.PickupMethod", "PickupMethod")
                        .WithMany("ProductPickupMethods")
                        .HasForeignKey("PickupMethodName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Products.Product", "Product")
                        .WithMany("ProductPickupMethods")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickupMethod");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Stores.Store", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Warehouses.Warehouse", "Warehouse")
                        .WithOne("Store")
                        .HasForeignKey("Chabloom.Ecommerce.Backend.Models.Stores.Store", "WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.TenantHost", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.Tenant", "Tenant")
                        .WithMany("Addresses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.TenantRole", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.TenantUser", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Warehouses.Warehouse", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Warehouses.WarehouseProduct", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Products.Product", "Product")
                        .WithMany("Warehouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Warehouses.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.TenantRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.TenantRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Chabloom.Ecommerce.Backend.Models.Tenants.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Orders.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductPickupMethods");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Products.ProductCategory", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Stores.PickupMethod", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductPickupMethods");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Stores.Store", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Tenants.Tenant", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Chabloom.Ecommerce.Backend.Models.Warehouses.Warehouse", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Store");
                });
#pragma warning restore 612, 618
        }
    }
}
